Update dependencies and simplify build process (#2)
* Make project compiling again by upgrading to next min version of kotlin and gradle and fix sample game `dodge` asset linking

To build and execute the project's samples refer to `COMPILING.md` and `GETTING_STARTED.md`.
Tldr:
- Make all `gradlew` files and `buildAll.sh` (`buildAll.bat` respectively) executable
- Execute `buildAll.sh` / `buildAll.bat`
- Copy generated sharedLib from `samples/games/kotlin/build/bin/<platform>/mainReleaseShared/` (`.so` and/or `.dll`) to `samples/games/project/`
- Open `samples/games/project/project.godot` in Godot Editor and run the game.

* Update gradle to version `6.0.1` and kotlin to `1.3.50` for all tools

* Update wrapper gradle to version `6.0.1` and kotlin to `1.3.61`

* Update tools kotlin version to `1.3.61`

* Use kotlinVersion variable for plugin version

* Fix `java.lang.NoSuchMethodError`...`HostManager.<init>`

TODO: make groovy autocompletion work and check if the autocompletion
works in kts.

* Update gradle to version `6.0.1` and kotlin to `1.3.61` in sample games and use fix version of `kotlin-godot` gradle plugin

* Update libnames

* Combine projects into one and cleanup dependencies between each other

* Cleanup and remove unused gradle wrappers and build settings of subprojects

* Remove now unused build scripts

* Fix `entry-generator` not published to maven local

* Make samples individually buildable

* Make build more type safe in order to prepare for migration to kts

* Migrate `godot-library` build script from groovy to kts

* Migrate `godot-library-extensions` build script from groovy to kts

* Migrate `godot-gradle-plugin` build script from groovy to kts

* Migrate `entry-generator` build script from groovy to kts

* Migrate `api-classes-generator` build script from groovy to kts

* Migrate `samples:games:kotlin` build script from groovy to kts

* Migrate `samples:coroutines:kotlin` build script from groovy to kts

* Remove unused dependencies and dead code

* Fix distribution of `godot-library-extension` and thus the coroutines sample

* Fix `generateGDNS` path to work with non gradle wrappers

* feature/update_dependencies: Remove platform specific kotlin native coroutines dependencies

As we do not need specific platform code, those can be removed from project.
Was also causing compilation error on windows